---
repos:
  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.2
    hooks:
      - id: update-docs

  - repo: local
    hooks:
      - id: generate-templates
        name: (Re)generate Portal Templates
        entry: ansible-playbook generate_template.yaml
        language: python
        pass_filenames: false
        additional_dependencies:
          - ansible-core

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        entry: env CI=1 bash -c "prettier --list-different . || ec=$? && prettier --log-level=error --write . && exit $ec"
        pass_filenames: false
        args: []
        exclude: ^extensions/mcp/servers\.yaml$
        additional_dependencies:
          - prettier
          - prettier-plugin-toml

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black
