---
# Parse mcp_servers input into common_mcp_roles list
# This task file can be included by both install_mcp.yml and tests

- name: Parse mcp_servers into common_mcp_roles list
  ansible.builtin.set_fact:
    common_mcp_roles: "{{ mcp_servers.split(',') if mcp_servers is defined else [] }}"
